version: '3.8'

services:
  # Backend API
  backend:
    build:
      context: .
      dockerfile: Dockerfile
      target: backend-build
    volumes:
      - ./backend:/app
      - ./storage:/app/storage
    ports:
      - "8000:8000"
    environment:
      - PYTHONPATH=/app
      - DEBUG=1
    command: uvicorn main:app --host 0.0.0.0 --port 8000 --reload
    networks:
      - footscan-network
    restart: unless-stopped
  
  # Frontend development server
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    volumes:
      - ./frontend:/app
      - /app/node_modules
    ports:
      - "3000:3000"
    environment:
      - REACT_APP_API_URL=http://localhost:8000
    depends_on:
      - backend
    networks:
      - footscan-network
    restart: unless-stopped
  
  # Redis for task queue
  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
    networks:
      - footscan-network
    restart: unless-stopped
  
  # Celery worker for background processing
  celery-worker:
    build:
      context: .
      dockerfile: Dockerfile
      target: backend-build
    volumes:
      - ./backend:/app
      - ./storage:/app/storage
    environment:
      - PYTHONPATH=/app
      - REDIS_HOST=redis
    command: celery -A tasks worker --loglevel=info
    depends_on:
      - redis
      - backend
    networks:
      - footscan-network
    restart: unless-stopped

networks:
  footscan-network:
    driver: bridge

volumes:
  storage: 